version: 2
updates:
  - package-ecosystem: cargo
    directory: /code/api
    schedule:
      interval: weekly
    groups:
      cargo:
        patterns: ["*"]

  - package-ecosystem: cargo
    directory: /code/worker
    schedule:
      interval: weekly
    groups:
      cargo:
        patterns: ["*"]

  - package-ecosystem: cargo
    directory: /code/cli
    schedule:
      interval: weekly
    groups:
      cargo:
        patterns: ["*"]

  - package-ecosystem: gomod
    directory: /code/dns-webhook
    schedule:
      interval: weekly
    groups:
      gomod:
        patterns: ["*"]

  - package-ecosystem: npm
    directory: /code/frontend
    schedule:
      interval: weekly
    groups:
      npm_and_yarn:
        patterns: ["*"]
    ignore:
      - dependency-name: eslint
        versions: [">=10.0.0"]

  - package-ecosystem: docker
    directory: /docker
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns: ["*"]
