//! Audit endpoint integration tests
//!
//! Covers:
//! - `GET /api/audit` — list audit logs (requires audit.view)
//! - `GET /api/audit/stats` — audit statistics (requires audit.view)
//! - Audit logs are generated by login activity

use axum::{
    body::Body,
    http::{header, Request, StatusCode},
};
use http_body_util::BodyExt;
use tower::util::ServiceExt;

mod common;
use common::{build_test_app_state_with_db, create_test_db_with_seed, create_test_user_with_role};

use kubarr::endpoints::create_router;

// ============================================================================
// JWT key initialization
// ============================================================================

static JWT_INIT: tokio::sync::OnceCell<()> = tokio::sync::OnceCell::const_new();

async fn ensure_jwt_keys() {
    JWT_INIT
        .get_or_init(|| async {
            let db = create_test_db_with_seed().await;
            kubarr::services::init_jwt_keys(&db)
                .await
                .expect("Failed to initialise test JWT keys");
        })
        .await;
}

// ============================================================================
// Helpers
// ============================================================================

/// POST /auth/login and return (status, Set-Cookie header value).
async fn do_login(
    app: axum::Router,
    username: &str,
    password: &str,
) -> (StatusCode, Option<String>) {
    let body = serde_json::json!({
        "username": username,
        "password": password
    })
    .to_string();

    let request = Request::builder()
        .uri("/auth/login")
        .method("POST")
        .header("content-type", "application/json")
        .body(Body::from(body))
        .unwrap();

    let response = app.oneshot(request).await.unwrap();
    let status = response.status();

    let cookie = response
        .headers()
        .get_all(header::SET_COOKIE)
        .iter()
        .find_map(|v| {
            let s = v.to_str().ok()?;
            if s.starts_with("kubarr_session=") && !s.contains("kubarr_session_") {
                Some(s.split(';').next().unwrap().to_string())
            } else {
                None
            }
        });

    (status, cookie)
}

/// Make an authenticated GET request and return (status, body).
async fn authenticated_get(app: axum::Router, uri: &str, cookie: &str) -> (StatusCode, String) {
    let request = Request::builder()
        .uri(uri)
        .method("GET")
        .header("Cookie", cookie)
        .body(Body::empty())
        .unwrap();

    let response = app.oneshot(request).await.unwrap();
    let status = response.status();
    let body = response.into_body().collect().await.unwrap().to_bytes();
    (status, String::from_utf8_lossy(&body).to_string())
}

// ============================================================================
// GET /api/audit — requires auth
// ============================================================================

#[tokio::test]
async fn test_get_audit_logs_requires_auth() {
    let db = create_test_db_with_seed().await;
    let state = build_test_app_state_with_db(db).await;
    let app = create_router(state);

    let response = app
        .oneshot(
            Request::builder()
                .uri("/api/audit")
                .method("GET")
                .body(Body::empty())
                .unwrap(),
        )
        .await
        .unwrap();

    assert_eq!(
        response.status(),
        StatusCode::UNAUTHORIZED,
        "GET /api/audit without a session cookie must return 401"
    );
}

// ============================================================================
// GET /api/audit — empty log on fresh DB
// ============================================================================

#[tokio::test]
async fn test_get_audit_logs_empty() {
    ensure_jwt_keys().await;

    let db = create_test_db_with_seed().await;
    create_test_user_with_role(
        &db,
        "auditadmin",
        "auditadmin@example.com",
        "password123",
        "admin",
    )
    .await;
    let state = build_test_app_state_with_db(db).await;

    let (login_status, cookie) =
        do_login(create_router(state.clone()), "auditadmin", "password123").await;
    assert_eq!(login_status, StatusCode::OK, "Login must succeed");
    let cookie = cookie.expect("Login must set a session cookie");

    let (status, body) = authenticated_get(create_router(state), "/api/audit", &cookie).await;

    assert_eq!(
        status,
        StatusCode::OK,
        "GET /api/audit must return 200 for admin. Body: {}",
        body
    );

    let json: serde_json::Value = serde_json::from_str(&body).unwrap();

    // Paginated response must include these top-level fields
    assert!(
        json.get("logs").is_some(),
        "Audit log response must include a 'logs' field. Body: {}",
        body
    );
    assert!(
        json.get("total").is_some(),
        "Audit log response must include a 'total' field. Body: {}",
        body
    );
    assert!(
        json.get("page").is_some(),
        "Audit log response must include a 'page' field. Body: {}",
        body
    );
    assert!(
        json.get("per_page").is_some(),
        "Audit log response must include a 'per_page' field. Body: {}",
        body
    );

    // The in-memory audit log starts empty (logs are written asynchronously
    // and the test AppState uses an in-memory AuditService, not a DB writer)
    let logs = json["logs"].as_array().unwrap();
    assert!(
        logs.len() < 100,
        "A fresh in-memory database must not have thousands of audit entries"
    );
}

// ============================================================================
// GET /api/audit/stats
// ============================================================================

#[tokio::test]
async fn test_get_audit_stats_as_admin() {
    ensure_jwt_keys().await;

    let db = create_test_db_with_seed().await;
    create_test_user_with_role(
        &db,
        "auditstatsadmin",
        "auditstats@example.com",
        "password123",
        "admin",
    )
    .await;
    let state = build_test_app_state_with_db(db).await;

    let (_, cookie) = do_login(
        create_router(state.clone()),
        "auditstatsadmin",
        "password123",
    )
    .await;
    let cookie = cookie.expect("Login must set a session cookie");

    let (status, body) = authenticated_get(create_router(state), "/api/audit/stats", &cookie).await;

    assert_eq!(
        status,
        StatusCode::OK,
        "GET /api/audit/stats must return 200 for admin. Body: {}",
        body
    );

    let json: serde_json::Value = serde_json::from_str(&body).unwrap();

    // Verify the stats object includes the expected fields
    assert!(
        json.get("total_events").is_some(),
        "Audit stats must include 'total_events'. Body: {}",
        body
    );
    assert!(
        json.get("successful_events").is_some(),
        "Audit stats must include 'successful_events'. Body: {}",
        body
    );
    assert!(
        json.get("failed_events").is_some(),
        "Audit stats must include 'failed_events'. Body: {}",
        body
    );
    assert!(
        json.get("events_today").is_some(),
        "Audit stats must include 'events_today'. Body: {}",
        body
    );
    assert!(
        json.get("top_actions").is_some(),
        "Audit stats must include 'top_actions'. Body: {}",
        body
    );
}

// ============================================================================
// GET /api/audit — audit log response shape after login activity
// ============================================================================

#[tokio::test]
async fn test_get_audit_logs_after_activity() {
    ensure_jwt_keys().await;

    let db = create_test_db_with_seed().await;
    create_test_user_with_role(
        &db,
        "activityadmin",
        "activity@example.com",
        "password123",
        "admin",
    )
    .await;
    let state = build_test_app_state_with_db(db).await;

    // Perform some activity: login a couple of times
    let (_, cookie) = do_login(create_router(state.clone()), "activityadmin", "password123").await;
    let cookie = cookie.expect("First login must set a session cookie");

    // Second login attempt (intentionally wrong password) — generates a failed event
    let _ = do_login(
        create_router(state.clone()),
        "activityadmin",
        "wrongpassword",
    )
    .await;

    // Now fetch the audit log
    let (status, body) = authenticated_get(create_router(state), "/api/audit", &cookie).await;

    assert_eq!(
        status,
        StatusCode::OK,
        "GET /api/audit must return 200 after activity. Body: {}",
        body
    );

    let json: serde_json::Value = serde_json::from_str(&body).unwrap();
    assert!(
        json.get("logs").is_some(),
        "Audit response must always include 'logs' field"
    );
    assert!(
        json.get("total").is_some(),
        "Audit response must always include 'total' field"
    );

    // The logs array must be an array (even if in-memory writes are async)
    assert!(
        json["logs"].is_array(),
        "Audit logs field must be a JSON array"
    );

    // total must be a non-negative integer
    let total = json["total"].as_u64().unwrap_or(0);
    assert!(
        total < u64::MAX,
        "Audit total must be a valid non-negative integer"
    );
}

// ============================================================================
// POST /api/audit/clear — clear old audit logs (lines 81-92 in audit.rs)
// ============================================================================

#[tokio::test]
async fn test_clear_audit_logs_succeeds_as_admin() {
    ensure_jwt_keys().await;

    let db = create_test_db_with_seed().await;
    create_test_user_with_role(
        &db,
        "clearauditadmin",
        "clearauditadmin@example.com",
        "password123",
        "admin",
    )
    .await;
    let state = build_test_app_state_with_db(db).await;

    let (_, cookie) = {
        let body = serde_json::json!({"username": "clearauditadmin", "password": "password123"})
            .to_string();
        let resp = create_router(state.clone())
            .oneshot(
                Request::builder()
                    .uri("/auth/login")
                    .method("POST")
                    .header("content-type", "application/json")
                    .body(Body::from(body))
                    .unwrap(),
            )
            .await
            .unwrap();
        let status = resp.status();
        let cookie = resp
            .headers()
            .get_all(header::SET_COOKIE)
            .iter()
            .find_map(|v| {
                let s = v.to_str().ok()?;
                if s.starts_with("kubarr_session=") && !s.contains("kubarr_session_") {
                    Some(s.split(';').next().unwrap().to_string())
                } else {
                    None
                }
            });
        (status, cookie)
    };
    let cookie = cookie.expect("Login must set a session cookie");

    let clear_body = serde_json::json!({ "days": 0 }).to_string();
    let response = create_router(state)
        .oneshot(
            Request::builder()
                .uri("/api/audit/clear")
                .method("POST")
                .header("Cookie", &cookie)
                .header("content-type", "application/json")
                .body(Body::from(clear_body))
                .unwrap(),
        )
        .await
        .unwrap();

    assert_eq!(
        response.status(),
        StatusCode::OK,
        "POST /api/audit/clear must return 200 for admin"
    );

    let body = response.into_body().collect().await.unwrap().to_bytes();
    let json: serde_json::Value = serde_json::from_str(&String::from_utf8_lossy(&body)).unwrap();

    assert!(
        json.get("deleted").is_some(),
        "Response must include 'deleted' count"
    );
    assert!(
        json.get("message").is_some(),
        "Response must include a 'message'"
    );
}

#[tokio::test]
async fn test_clear_audit_logs_with_default_days() {
    ensure_jwt_keys().await;

    let db = create_test_db_with_seed().await;
    create_test_user_with_role(
        &db,
        "clearauditdefault",
        "clearauditdefault@example.com",
        "password123",
        "admin",
    )
    .await;
    let state = build_test_app_state_with_db(db).await;

    let (_, cookie) = {
        let body = serde_json::json!({"username": "clearauditdefault", "password": "password123"})
            .to_string();
        let resp = create_router(state.clone())
            .oneshot(
                Request::builder()
                    .uri("/auth/login")
                    .method("POST")
                    .header("content-type", "application/json")
                    .body(Body::from(body))
                    .unwrap(),
            )
            .await
            .unwrap();
        let cookie = resp
            .headers()
            .get_all(header::SET_COOKIE)
            .iter()
            .find_map(|v| {
                let s = v.to_str().ok()?;
                if s.starts_with("kubarr_session=") && !s.contains("kubarr_session_") {
                    Some(s.split(';').next().unwrap().to_string())
                } else {
                    None
                }
            });
        (resp.status(), cookie)
    };
    let cookie = cookie.expect("Login must set a session cookie");

    // Send without `days` to exercise the `None → 90` default path
    let clear_body = serde_json::json!({}).to_string();
    let response = create_router(state)
        .oneshot(
            Request::builder()
                .uri("/api/audit/clear")
                .method("POST")
                .header("Cookie", &cookie)
                .header("content-type", "application/json")
                .body(Body::from(clear_body))
                .unwrap(),
        )
        .await
        .unwrap();

    assert_eq!(
        response.status(),
        StatusCode::OK,
        "POST /api/audit/clear without days must use default (90) and return 200"
    );
}
